spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payment-service
    username: postgres
    password: test123
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8084